---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: crier
  name: crier
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crier
    spec:
      affinity: {}
      containers:
        - args:
            - "--blob-storage-workers=10"
            - "--config-path=/etc/config/config.yaml"
            - "--s3-credentials-file=/etc/s3-credentials/service-account.json"
            - "--github-endpoint=http://ghproxy"
            - "--github-endpoint=https://api.github.com"
            - "--github-token-path=/etc/github/token"
            - "--github-workers=10"
            - "--kubernetes-blob-storage-workers=10"
          image: quay.io/prow/crier:kustomization-overlay
          livenessProbe:
            failureThreshold: 3
            # httpGet:
            #   path: /healthz
            #   port: 8081
            #   scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6060
            timeoutSeconds: 1
          name: crier
          ports:
            - containerPort: 8081
              name: health
              protocol: TCP
            - containerPort: 6060
              name: pprof
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            # httpGet:
            #   path: /healthz
            #   port: 8081
            #   scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6060
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 256M
            requests:
              cpu: 5m
              memory: 128M
          volumeMounts:
            - mountPath: /etc/config
              name: config
              readOnly: true
            - mountPath: /etc/github
              name: github-token
              readOnly: true
            - mountPath: /etc/s3-credentials
              name: s3-credentials
              readOnly: true
      serviceAccountName: crier
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            name: config
          name: config
        - name: github-token
          secret:
            items:
              - key: oauth
                path: token
            secretName: github-tokens

        - name: s3-credentials
          secret:
            items:
              - key: service-account.json
                path: service-account.json
            secretName: s3-credentials
