---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ghproxy
  name: ghproxy
  namespace: prow
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ghproxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ghproxy
    spec:
      containers:
        - args:
            - "--cache-dir=/cache"
            - "--cache-sizeGB=19"
            - "--serve-metrics=true"
            - "--legacy-disable-disk-cache-partitions-by-auth-header=false"
          image: quay.io/prow/ghproxy:v20241011-24e765300-dirty
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: ghproxy
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
            - containerPort: 8081
              name: health
              protocol: TCP
            - containerPort: 6060
              name: pprof
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 128M
            requests:
              cpu: 5m
              memory: 32M
          volumeMounts:
            - mountPath: /cache
              name: cache
      volumes:
        - name: cache
          persistentVolumeClaim:
            claimName: ghproxy
