---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ghproxy
  name: ghproxy
  namespace: prow
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
    - name: metrics
      port: 9090
  selector:
    app.kubernetes.io/name: ghproxy
  type: ClusterIP
