---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: hook
  name: hook
  namespace: prow
spec:
  ports:
    - name: http
      port: 8888
  selector:
    app.kubernetes.io/name: hook
