---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  data:
    - remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: service-account.json
      secretKey: service-account.json
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mgmt
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: s3-credentials
