apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crier.yaml
  - deck.yaml
  - hook.yaml
  - horologium.yaml
  - prow-controller-manager.yaml
  - sinker.yaml
  - statusreconciler.yaml
  - tide.yaml
