apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: prow
resources:
  - github-tokens.yaml
  - s3-credentials.yaml
