apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_ACCESS_KEY_ID
      secretKey: AWS_ACCESS_KEY_ID
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_REGION
      secretKey: AWS_BUCKET_REGION
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_NAME
      secretKey: AWS_BUCKET_NAME
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_DOMAIN
      secretKey: AWS_BUCKET_DOMAIN
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: service-account.json
      secretKey: service-account.json
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mgmt
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: s3-credentials
