---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: tide
  name: tide
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tide
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tide
    spec:
      affinity: {}
      containers:
        - args:
            - "--dry-run=false"
            - "--config-path=/etc/config/config.yaml"
            - "--github-token-path=/etc/github/token"
            - "--github-endpoint=http://ghproxy"
            - "--github-endpoint=https://api.github.com"
            - "--github-graphql-endpoint=http://ghproxy/graphql"
            - "--s3-credentials-file=/etc/s3-credentials/service-account.json"
            - "--status-path=s3://3scale-mgmt-prow/tide/tide-status"
            - "--history-uri=s3://3scale-mgmt-prow/tide/tide-history.json"
          image: quay.io/prow/tide:kustomization-overlay
          name: tide
          ports:
            - containerPort: 8888
              name: http
          resources:
            limits:
              cpu: 500m
              memory: 128M
            requests:
              cpu: 10m
              memory: 64M
          volumeMounts:
            - mountPath: /etc/github
              name: github-token
              readOnly: true
            - mountPath: /etc/config
              name: config
              readOnly: true
            - mountPath: /etc/s3-credentials
              name: s3-credentials
              readOnly: true
      serviceAccountName: tide
      volumes:
        - name: github-token
          secret:
            items:
              - key: oauth
                path: token
            secretName: github-tokens
        - configMap:
            name: config
          name: config
        - name: s3-credentials
          secret:
            items:
              - key: service-account.json
                path: service-account.json
            secretName: s3-credentials
