---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: tide
  name: tide
  namespace: prow
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app.kubernetes.io/name: tide
