---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deck
  namespace: prow-test-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck
subjects:
  - kind: ServiceAccount
    name: deck
    namespace: prow
