---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/target: prow.apps.rosa.pro-base-rosa.73b2.p3.openshiftapps.com
  labels:
    app.kubernetes.io/name: prow
    type: internal
  name: prow
  namespace: prow
spec:
  ingressClassName: openshift-default
  rules:
    - host: prow.mgmt.3sca.net
      http:
        paths:
          - backend:
              service:
                name: deck
                port:
                  name: http
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - prow.mgmt.3sca.net
      secretName: prow-ingress-tls
