---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: prow-hook.mgmt.3sca.net
    external-dns.alpha.kubernetes.io/target: prow-hook.external.pro-base-ocp4.mgmt.3sca.net
  name: prow-hook
  namespace: prow
  labels:
    type: external
spec:
  rules:
  - host: prow-hook.mgmt.3sca.net
    http:
      paths:
      - path: /hook
        pathType: ImplementationSpecific
        backend:
          service:
            name: hook
            port:
              name: http
  tls:
  - hosts:
    - prow-hook.mgmt.3sca.net
    secretName: prow-hook-ingress-tls
