---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: prow-hook.mgmt.3sca.net
    external-dns.alpha.kubernetes.io/target: prow-hook.external.rosa.pro-base-rosa.73b2.p3.openshiftapps.com
  labels:
    app.kubernetes.io/name: prow-hook
    type: external
  name: prow-hook
  namespace: prow
spec:
  ingressClassName: openshift-external
  rules:
    - host: prow-hook.mgmt.3sca.net
      http:
        paths:
          - backend:
              service:
                name: hook
                port:
                  name: http
            path: /hook
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - prow-hook.mgmt.3sca.net
      secretName: prow-hook-ingress-tls
