---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: prow-hook.mgmt.3sca.net
    external-dns.alpha.kubernetes.io/target: prow-hook.apps.pro-base-ocp4.mgmt.3sca.net
  name: prow-hook
  namespace: prow
spec:
  rules:
  - host: prow-hook.mgmt.3sca.net
    http:
      paths:
      - backend:
          serviceName: hook
          servicePort: http
        path: /hook
  tls:
  - hosts:
    - prow-hook.mgmt.3sca.net
    secretName: prow-hook-ingress-tls
