---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: statusreconciler
  name: statusreconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: statusreconciler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: statusreconciler
    spec:
      affinity: {}
      containers:
        - args:
            - "--dry-run=false"
            - "--continue-on-error=true"
            - "--plugin-config=/etc/plugins/plugins.yaml"
            - "--config-path=/etc/config/config.yaml"
            - "--github-token-path=/etc/github/token"
            - "--github-endpoint=http://ghproxy"
            - "--github-endpoint=https://api.github.com"
            - "--s3-credentials-file=/etc/s3-credentials/service-account.json"
            - "--status-path=s3://3scale-mgmt-prow/status-reconciler/status-reconciler-status"
          image: quay.io/prow/status-reconciler:kustomization-overlay
          livenessProbe:
            failureThreshold: 3
            # httpGet:
            #   path: /healthz
            #   port: 8081
            #   scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6060
            timeoutSeconds: 1
          name: statusreconciler
          ports:
            # - containerPort: 8081
            #   name: health
            #   protocol: TCP
            - containerPort: 6060
              name: pprof
              protocol: TCP
            - containerPort: 9090
              name: metrics
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            # httpGet:
            #   path: /healthz
            #   port: 8081
            #   scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 6060
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 64M
            requests:
              cpu: 5m
              memory: 32M
          volumeMounts:
            - mountPath: /etc/github
              name: github-token
              readOnly: true
            - mountPath: /etc/config
              name: config
              readOnly: true
            - mountPath: /etc/plugins
              name: plugins
              readOnly: true
            - mountPath: /etc/s3-credentials
              name: s3-credentials
              readOnly: true
      serviceAccountName: statusreconciler
      terminationGracePeriodSeconds: 180
      volumes:
        - name: github-token
          secret:
            items:
              - key: oauth
                path: token
            secretName: github-tokens
        - configMap:
            name: config
          name: config
        - configMap:
            name: plugins
          name: plugins
        - name: s3-credentials
          secret:
            items:
              - key: service-account.json
                path: service-account.json
            secretName: s3-credentials
