---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: statusreconciler
  name: statusreconciler
  namespace: prow
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: statusreconciler
subjects:
  - kind: ServiceAccount
    name: statusreconciler
