---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: horologium
  name: horologium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: horologium
subjects:
  - kind: ServiceAccount
    name: horologium
