apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: github-tokens
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: vault-mgmt
    kind: ClusterSecretStore
  target:
    name: github-tokens
  data:
  - secretKey: oauth
    remoteRef:
      key: kubernetes/pro-base/ocp4/prow/github-tokens
      property: oauth
  - secretKey: hmac
    remoteRef:
      key: kubernetes/pro-base/ocp4/prow/github-tokens
      property: hmac