apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-tokens
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: vault-mgmt
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: github-tokens
  data:
    - secretKey: oauth
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/github-tokens
        property: oauth
    - secretKey: hmac
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/github-tokens
        property: hmac
