apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  refreshInterval: 1m0s
  secretStoreRef:
    name: vault-mgmt
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: s3-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_BUCKET_REGION
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_REGION
    - secretKey: AWS_BUCKET_NAME
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_NAME
    - secretKey: AWS_BUCKET_DOMAIN
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: AWS_BUCKET_DOMAIN
    - secretKey: service-account.json
      remoteRef:
        key: kubernetes/pro-base/rosa/prow/3scale-pro-base-prow-s3-credentials
        property: service-account.json
