apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  labels:
    app.kubernetes.io/name: prow
  name: probe-http-priv-ingress-prow
spec:
  interval: 30s
  module: http_2xx
  prober:
    path: /probe
    url: "prometheus-exporter-probe-pro-base-blackbox.prometheus-exporter.svc:9115"
  targets:
    staticConfig:
      static:
        - "https://prow.mgmt.3sca.net"
