apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prow-controller-manager
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: kubernetes/pro-base/rosa/prow/prow-controller-manager
        property: kubeconfig
      secretKey: kubeconfig
  refreshInterval: 1m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-mgmt
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: prow-controller-manager
