---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: crier
  namespace: prow-test-pods
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - events
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - patch