---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prow-controller-manager
  namespace: prow-test-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - create
      - patch
