---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: sinker
  namespace: prow-test-pods
rules:
- apiGroups:
  - ''
  resources:
  - pods
  verbs:
  - delete
  - list
  - watch
  - get
  - patch