apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  app.kubernetes.io/created-by: argocd
  app.kubernetes.io/environment: pro-base
  app.kubernetes.io/managed-by: argocd
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: prow
      app.kubernetes.io/name: prow-jobs
kind: Kustomization
namespace: prow-test-pods
resources:
  - common
  - crier
  - deck
  - prow-controller-manager
  - sinker
