apiVersion: kustomize.config.k8s.io/v1beta1
commonAnnotations:
  app.kubernetes.io/created-by: argocd
  app.kubernetes.io/environment: pro-base
  app.kubernetes.io/managed-by: argocd
commonLabels:
  app.kubernetes.io/name: prow-jobs
kind: Kustomization
resources:
  - externalsecrets
  - rolebindings
  - roles
