kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
  name: aggregate-prow-k8s-io-view
rules:
  - apiGroups:
      - prow.k8s.io
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
