---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plugins
  namespace: prow
data:
  plugins.yaml: |
    plugins:
      3scale-ops:
      - approve
      - assign
      - blunderbuss
      - branchcleaner
      - mergecommitblocker
      - cat
      - dog
      - help
      - heart
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - require-matching-label
      - retitle
      - shrug
      - trigger
      - verify-owners
      - wip
      - yuks
      3scale/3scale-saas:
      - approve
      - assign
      - blunderbuss
      - mergecommitblocker
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - require-matching-label
      - retitle
      - trigger
      - verify-owners
      - wip
      3scale/platform:
      - approve
      - assign
      - blunderbuss
      - mergecommitblocker
      - help
      - hold
      - invalidcommitmsg
      - label
      - lgtm
      - lifecycle
      - require-matching-label
      - retitle
      - trigger
      - verify-owners
      - wip

    require_matching_label:
      - missing_label: needs-kind
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^kind/
        missing_comment: |
          There are no kind on this issue.
          Please add an appropriate kind by using one of the following commands:
            - `/kind bug`
            - `/kind cleanup`
            - `/kind documentation`
            - `/kind feature`
            - `/kind <kind-name>`
      - missing_label: needs-priority
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^priority/
      - missing_label: needs-size
        org: 3scale-ops
        issues: true
        prs: true
        regexp: ^size/
      - missing_label: needs-kind
        org: 3scale
        issues: true
        prs: true
        regexp: ^kind/
        missing_comment: |
          There are no kind on this issue.
          Please add an appropriate kind by using one of the following commands:
            - `/kind bug`
            - `/kind cleanup`
            - `/kind documentation`
            - `/kind feature`
            - `/kind <kind-name>`
      - missing_label: needs-priority
        org: 3scale
        issues: true
        prs: true
        regexp: ^priority/
      - missing_label: needs-size
        org: 3scale
        issues: true
        prs: true
        regexp: ^size/
      - missing_label: needs-env
        org: 3scale/
        issues: true
        prs: true
        regexp: ^env/
      - missing_label: needs-layer
        org: 3scale/platform
        issues: true
        prs: true
        regexp: ^layer/

    approve:
      - repos:
          - 3scale
          - 3scale-ops

        commandHelpLink: "https://prow.mgmt.3sca.net/command-help"

        # RequireSelfApproval requires PR authors to explicitly approve their PRs.
        # Otherwise the plugin assumes the author of the PR approves the changes in the PR.
        require_self_approval: true

        # IgnoreReviewState causes the approve plugin to ignore the GitHub review state. Otherwise:
        # * an APPROVE github review is equivalent to leaving an "/approve" message.
        # * A REQUEST_CHANGES github review is equivalent to leaving an /approve cancel" message.
        ignore_review_state: true

    lgtm:
      - repos:
          - 3scale
          - 3scale-ops

        # ReviewActsAsLgtm indicates that a GitHub review of "approve" or "request changes"
        # acts as adding or removing the lgtm label
        review_acts_as_lgtm: true

        # StoreTreeHash indicates if tree_hash should be stored inside a comment to detect
        # squashed commits before removing lgtm labels
        store_tree_hash: true
